---
title: "ld_analysis"
author: "sq-96"
date: "2021-07-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
```{r,message=FALSE,results=FALSE,echo=FALSE,eval=FALSE}
set.seed(2021)
sample_list <- read.table("/project2/xinhe/1kg/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.fam",header=FALSE,sep=" ")
sample_list <- sample_list[sample(1:489,480),c("V1","V2")]
sample_list_split <- split(sample_list, sample(rep(1:3,times=c(160,160,160))))
subsample1 <- sample_list_split$`1`
subsample2 <- sample_list_split$`2`
subsample3 <- sample_list_split$`3`

write.table(subsample1,file = "./data/EUR_subpop1.txt",sep='\t',quote = FALSE,col.names = FALSE,row.names = FALSE)
write.table(subsample2,file = "./data/EUR_subpop2.txt",sep='\t',quote = FALSE,col.names = FALSE,row.names = FALSE)
write.table(subsample3,file = "./data/EUR_subpop3.txt",sep='\t',quote = FALSE,col.names = FALSE,row.names = FALSE)
```

```{r,message=FALSE,results=FALSE,echo=FALSE,eval=FALSE}
system("/software/plink-1.90-el7-x86_64/plink --bfile /project2/xinhe/1kg/1000G_EUR_Phase3_plink/1000G.EUR.QC.8 --keep ./data/EUR_subpop1.txt --chr 8 --from-bp 4177794 --to-bp 4192544 --write-snplist --maf 0.05 --r2 --matrix --out ./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop1")

system("/software/plink-1.90-el7-x86_64/plink --bfile /project2/xinhe/1kg/1000G_EUR_Phase3_plink/1000G.EUR.QC.8 --keep ./data/EUR_subpop2.txt --chr 8 --from-bp 4177794 --to-bp 4192544 --write-snplist --maf 0.05 --r2 --matrix --out ./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop2")

system("/software/plink-1.90-el7-x86_64/plink --bfile /project2/xinhe/1kg/1000G_EUR_Phase3_plink/1000G.EUR.QC.8 --keep ./data/EUR_subpop3.txt --chr 8 --from-bp 4177794 --to-bp 4192544 --write-snplist --maf 0.05 --r2 --matrix --out ./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop3")

system("/software/plink-1.90-el7-x86_64/plink --bfile /project2/xinhe/1kg/1000G_EUR_Phase3_plink/1000G.EUR.QC.8 --chr 8 --from-bp 4177794 --to-bp 4192544 --write-snplist --maf 0.05 --r2 --matrix --out ./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR")
```

```{r,message=FALSE,results=FALSE,echo=FALSE}
ld1 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop1.ld',header=FALSE)
snp_list1 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop1.snplist',header=FALSE)
colnames(ld1) <- snp_list1$V1
rownames(ld1) <- snp_list1$V1

ld2 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop2.ld',header=FALSE)
snp_list2 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop2.snplist',header=FALSE)
colnames(ld2) <- snp_list2$V1
rownames(ld2) <- snp_list2$V1

ld3 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop3.ld',header=FALSE)
snp_list3 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR_subpop3.snplist',header=FALSE)
colnames(ld3) <- snp_list3$V1
rownames(ld3) <- snp_list3$V1

ld4 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR.ld',header=FALSE)
snp_list4 <- read.table('./data/chr8_4177794_4192544_EUR/chr8_4177794_4192544_EUR.snplist',header=FALSE)
colnames(ld4) <- snp_list4$V1
rownames(ld4) <- snp_list4$V1
```

```{r,message=FALSE,results=FALSE,echo=FALSE}
index <- Reduce(intersect, list(snp_list1$V1,snp_list2$V1,snp_list3$V1,snp_list4$V1))
ld1 <- ld1[index,index]
ld2 <- ld2[index,index]
ld3 <- ld3[index,index]
ld4 <- ld4[index,index]

result1 <- eigen(ld1)
result2 <- eigen(ld2)
result3 <- eigen(ld3)
result4 <- eigen(ld4)

value1 <- round(result1$values,3)
value2 <- round(result2$values,3)
value3 <- round(result3$values,3)
value4 <- round(result4$values,3)

vector1 <- result1$vectors
vector2 <- result2$vectors
vector3 <- result3$vectors
vector4 <- result4$vectors
```

```{r}
rbind(value1[1:20],value2[1:20],value3[1:20],value4[1:20])
```

```{r,fig.height=10, fig.width=10,echo=FALSE}
library(plot.matrix)
library(RColorBrewer)
par(mar=c(5, 4, 4, 2),mfrow=c(2,2))
plot(as.matrix(ld1), axis.col=NULL, axis.row=NULL, xlab='', ylab='', main='EUR_sub1', col=brewer.pal(5,name = "Reds"),spacing.key=c(2,2,1))
plot(as.matrix(ld2), axis.col=NULL, axis.row=NULL, xlab='', ylab='', main='EUR_sub2', col=brewer.pal(5,name = "Reds"),spacing.key=c(2,2,1))
plot(as.matrix(ld3), axis.col=NULL, axis.row=NULL, xlab='', ylab='', main='EUR_sub3', col=brewer.pal(5,name = "Reds"),spacing.key=c(2,2,1))
plot(as.matrix(ld4), axis.col=NULL, axis.row=NULL, xlab='', ylab='', main='EUR_All', col=brewer.pal(5,name = "Reds"),spacing.key=c(2,2,1))
```



